dependencies:
    - name: hello
      version: 9.9.95
      repository: http://172.31.21.18:8080
      condition: hello.enabled
      tags:
        - gosrv
    - name: nginx
      version: 9.9.93
      repository: http://172.31.21.18:8080
      condition: nginx.enabled
      tags:
        - websrv