dependencies:
    - name: hellosrv
      version: 1.0.1
      repository: https://heinigai.github.io/testing-helm/
      condition: hellosrv.enabled
      tags:
        - gosrv
    - name: nginxsrv
      version: 1.0.1
      repository: https://heinigai.github.io/testing-helm/
      condition: nginxsrv.enabled
      tags:
        - websrv