dependencies:
    - name: hello
    #   version: 0.1.1
    #   version: alpha.1+33943
      version: 7ccc9f99d7ab6b9554624985d9c9b9723b7253c0
    #   version: alpha+7ccc9f99d7ab6b9554624985d9c9b9723b7253c0
      repository: https://heinigai.github.io/testing-helm/
      condition: hello.enabled
      tags:
        - gosrv
    - name: nginxsrv
      version: 1.0.3
      repository: https://heinigai.github.io/testing-helm/
      condition: nginxsrv.enabled
      tags:
        - websrv