dependencies:
    - name: hello
      version: 9.9.9
      repository: https://heinigai.github.io/testing-helm/
      condition: hello.enabled
      tags:
        - gosrv
    - name: nginx
      version: 9.9.9
      repository: https://heinigai.github.io/testing-helm/
      condition: nginx.enabled
      tags:
        - websrv