apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.port }}
      targetPort: {{ .Values.global.port }}
      protocol: TCP
      # name: http
  selector:
    {{- include "hello.selectorLabels" . | nindent 4 }}
