envType: ""
global:
  affinityKey: klook-travellerpltm.test.klook.io/team
  affinityValue: test
imageUrl: 172.31.17.229:5000/billtest
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 5000
  type: ClusterIP
serviceAccount:
  create: false
  name: null
tolerations: []
