# Default values for billtest-front.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 172.31.17.229:5000/billtest:nginx
  pullPolicy: Always

nameOverride: "nginx"
fullnameOverride: "nginx"

serviceAccount:
  # Specifies whether a service account should be created
  create: false

service:
  type: ClusterIP
  port: 80
  name: nginx

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: dev193.test.klook.io
      paths: [/]
  tls: []
